apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kubetime-agent
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: kubetime-agent
  template:
    metadata:
      labels:
        app: kubetime-agent
    spec:
      serviceAccountName: kubetime-agent

      # ✅ CRITICAL FOR NODE VISIBILITY
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet

      tolerations:
        - operator: "Exists"

      containers:
        - name: agent
          image: {{ .Values.agent.image }}
          imagePullPolicy: Always
          env:
            - name: BACKEND_URL
              value: {{ .Values.backend.url | quote }}

            - name: COMPANY_ID
              value: {{ .Values.agent.env.COMPANY_ID | quote }}

          resources:
{{ toYaml .Values.agent.resources | indent 12 }}
