apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubetime-agent
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubetime-agent
rules:
  # ================= CORE =================
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/status
      - nodes/proxy
      - pods
      - pods/status
      - services
      - endpoints
      - namespaces
      - serviceaccounts
      - events
    verbs: ["get", "list", "watch"]

  # ================= APPS =================
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs: ["get", "list", "watch"]

  # ================= BATCH =================
  - apiGroups: ["batch"]
    resources:
      - jobs
      - cronjobs
    verbs: ["get", "list", "watch"]

  # ================= COORDINATION =================
  - apiGroups: ["coordination.k8s.io"]
    resources:
      - leases
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubetime-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubetime-agent
subjects:
  - kind: ServiceAccount
    name: kubetime-agent
    namespace: {{ .Values.namespace }}
