apiVersion: v1
kind: ServiceAccount
metadata:
  name: kubetime-agent
  namespace: {{ .Values.namespace }}

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kubetime-agent
rules:
  # Core resources
  - apiGroups: [""]
    resources:
      - nodes
      - nodes/status
      - pods
      - pods/status
      - services
      - namespaces
      - events
    verbs: ["get", "list", "watch"]

  # Workloads
  - apiGroups: ["apps"]
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kubetime-agent
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kubetime-agent
subjects:
  - kind: ServiceAccount
    name: kubetime-agent
    namespace: {{ .Values.namespace }}
