apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubetime-backend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.backend.replicas }}
  selector:
    matchLabels:
      app: kubetime-backend
  template:
    metadata:
      labels:
        app: kubetime-backend
    spec:
      containers:
        - name: backend
          image: {{ .Values.backend.image }}
          ports:
            - containerPort: 8000
