apiVersion: v1
kind: Service
metadata:
  name: kubetime-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: kubetime-backend
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
  type: {{ .Values.backend.service.type }}
